### ISSUE TITLE
Key Binding Not Toggling Shader

### ISSUE THREAD

**Issue by LanceMcCarthy** [Hammster/windows-terminal-shaders#4]
I don't know if this is a Terminal problem or the shader pipeline problem, but Shift + F11 is not toggling the shader to turn off (it is stuck on). 

PS: I know key bindings are working in general because the Shift + F10 does invoke focus mode.

Just to make sure there isn't a syntax or command issue, here's the section from my settings.json

![image](https://user-images.githubusercontent.com/3520532/112721642-677a9180-8edb-11eb-818d-1bcc86f9b22f.png)

**Comment by Hammster** [comment]
Hi, so I certainly don't see a typo in there :) 

I'm to assume you've either:

- Hit a bug with the Terminal
- The hotkey `shift+f10` is used globally in your system by another program, try setting the `toggleShaderEffects` to `shift+f11` and report back if that helps

Cheers :)

**Comment by dadiego** [comment]
having the same problem here

**Comment by LanceMcCarthy** [comment]
@Hammster silly me, I should have tried that first 😂 Indeed, after I swapped the key binding to use F10, it worked fine.  

Note, I do not have any custom bindings for F11, so it might be a default for something else. It still might be worth looking into?

**Comment by Hammster** [comment]
The terminal team or I can't really do anything if any other software blocks the key bind globally, most software only do this when their window is focused unless it's something like an app search bar.

I'll consider this one closed for now 🙂 if you still find something that is caused by my shader or config feel free to update.
